apiVersion: v1
kind: Service 
metadata:
  name: flask-webapp-node-port-service
spec:
  type: NodePort # ClusterIp, # NodePort
  selector:
    app: flask-webapp
  ports:
    - name: http
      port: 5000 # Service Port
      targetPort: 5000 # Container Port
      nodePort: 32100
