apiVersion: v1
kind: Secret
metadata:
  name: flask-webapp-secret
data:
  # writer env
  WRITE_DB_USER: ZHVvbmdkeA==
  WRITE_DB_PASSWORD: ZHVvbmdkeDE=

  # reader env
  READ_DB_USER: ZHVvbmdkeA==
  READ_DB_PASSWORD: ZHVvbmdkeDE=

  # database env
  DB_NAME: d2ViYXBwZGI=
  DB_PORT: MzMwNgo=
