apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp2-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer 
parameters:
  type: gp2
reclaimPolicy: Delete
mountOptions:
  - debug
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - ap-southeast-1a
    - ap-southeast-1b
    - ap-southeast-1c

# STORAGE CLASS
# 1. A StorageClass provides a way for administrators
# to describe the "classes" of storage they offer.
# 2. Here we are offering EBS Storage for EKS Cluster
