apiVersion: v1
kind: Service 
metadata:
  name: webserver-nlb-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: NLB    # To create Network Load Balancer
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
